export const registerFormControls = [
  {
    name: "userName",
    label: "User Name",
    placeholder: "Enter your user name",
    componentType: "input",
    type: "text",
  },
  {
    name: "email",
    label: "Email",
    placeholder: "Enter your email",
    componentType: "input",
    type: "email",
  },
  {
    name: "password",
    label: "Password",
    placeholder: "Enter your password",
    componentType: "input",
    type: "password",
  },
];

export const loginFormControls = [
  {
    name: "email",
    label: "Email",
    placeholder: "Enter your email",
    componentType: "input",
    type: "email",
  },
  {
    name: "password",
    label: "Password",
    placeholder: "Enter your password",
    componentType: "input",
    type: "password",
  },
];

export const addProductFormElements = [
  {
    label: "Title",
    name: "title",
    componentType: "input",
    type: "text",
    placeholder: "Enter product title",
  },
  {
    label: "Description",
    name: "description",
    componentType: "textarea",
    placeholder: "Enter product description",
  },
  {
    label: "Category",
    name: "category",
    componentType: "select",
    options: [
      { id: "painting", label: "Painting Supplies" },
      { id: "drawing", label: "Drawing Supplies" },
      { id: "sculpting", label: "Sculpting & Modeling" },
      { id: "canvas", label: "Canvas & Surfaces" },
      { id: "paper", label: "Paper & Journals" },
      { id: "calligraphy", label: "Calligraphy" },
      { id: "embroidery", label: "Embroidery" },
      { id: "knitting", label: "Knitting & Crochet" },
      { id: "macrame", label: "Macrame" },
      { id: "resin", label: "Resin Art" },
      { id: "markers", label: "Markers & Pens" },
      { id: "accessories", label: "Art Accessories" },
    ],
  },
  {
    label: "Brand",
    name: "brand",
    componentType: "select",
    options: [
      { id: "artmaster", label: "ArtMaster" },
      { id: "colorflow", label: "ColorFlow" },
      { id: "sketchpro", label: "SketchPro" },
      { id: "canvascraft", label: "CanvasCraft" },
      { id: "claymaster", label: "ClayMaster" },
      { id: "writeart", label: "WriteArt" },
      { id: "threadcraft", label: "ThreadCraft" },
      { id: "brushmaster", label: "BrushMaster" },
      { id: "journalpro", label: "JournalPro" },
      { id: "colorpro", label: "ColorPro" },
      { id: "clayworks", label: "ClayWorks" },
      { id: "markerart", label: "MarkerArt" },
      { id: "knitcraft", label: "KnitCraft" },
      { id: "gouachepro", label: "GouachePro" },
      { id: "studiopro", label: "StudioPro" },
      { id: "charcoalart", label: "CharcoalArt" },
      { id: "resincraft", label: "ResinCraft" },
      { id: "origamipro", label: "OrigamiPro" },
      { id: "macramecrft", label: "MacrameCraft" },
      { id: "knifemaster", label: "KnifeMaster" },
    ],
  },
  {
    label: "Price",
    name: "price",
    componentType: "input",
    type: "number",
    placeholder: "Enter product price",
  },
  {
    label: "Sale Price",
    name: "salePrice",
    componentType: "input",
    type: "number",
    placeholder: "Enter sale price (optional)",
  },
  {
    label: "Total Stock",
    name: "totalStock",
    componentType: "input",
    type: "number",
    placeholder: "Enter total stock",
  },
];

export const shoppingViewHeaderMenuItems = [
  {
    id: "home",
    label: "Home",
    path: "/shop/home",
  },
  {
    id: "products",
    label: "All Products",
    path: "/shop/listing",
  },
  {
    id: "painting",
    label: "Painting",
    path: "/shop/listing",
  },
  {
    id: "drawing",
    label: "Drawing",
    path: "/shop/listing",
  },
  {
    id: "sculpting",
    label: "Sculpting",
    path: "/shop/listing",
  },
  {
    id: "crafts",
    label: "Crafts",
    path: "/shop/listing",
  },
  {
    id: "accessories",
    label: "Accessories",
    path: "/shop/listing",
  },
  {
    id: "search",
    label: "Search",
    path: "/shop/search",
  },
];

export const categoryOptionsMap = {
  painting: "Painting Supplies",
  drawing: "Drawing Supplies",
  sculpting: "Sculpting & Modeling",
  canvas: "Canvas & Surfaces",
  paper: "Paper & Journals",
  calligraphy: "Calligraphy",
  embroidery: "Embroidery",
  knitting: "Knitting & Crochet",
  macrame: "Macrame",
  resin: "Resin Art",
  markers: "Markers & Pens",
  accessories: "Art Accessories",
};

export const brandOptionsMap = {
  artmaster: "ArtMaster",
  colorflow: "ColorFlow",
  sketchpro: "SketchPro",
  canvascraft: "CanvasCraft",
  claymaster: "ClayMaster",
  writeart: "WriteArt",
  threadcraft: "ThreadCraft",
  brushmaster: "BrushMaster",
  journalpro: "JournalPro",
  colorpro: "ColorPro",
  clayworks: "ClayWorks",
  markerart: "MarkerArt",
  knitcraft: "KnitCraft",
  gouachepro: "GouachePro",
  studiopro: "StudioPro",
  charcoalart: "CharcoalArt",
  resincraft: "ResinCraft",
  origamipro: "OrigamiPro",
  macramecrft: "MacrameCraft",
  knifemaster: "KnifeMaster",
};

export const filterOptions = {
  category: [
    { id: "painting", label: "Painting Supplies" },
    { id: "drawing", label: "Drawing Supplies" },
    { id: "sculpting", label: "Sculpting & Modeling" },
    { id: "canvas", label: "Canvas & Surfaces" },
    { id: "paper", label: "Paper & Journals" },
    { id: "calligraphy", label: "Calligraphy" },
    { id: "embroidery", label: "Embroidery" },
    { id: "knitting", label: "Knitting & Crochet" },
    { id: "macrame", label: "Macrame" },
    { id: "resin", label: "Resin Art" },
    { id: "markers", label: "Markers & Pens" },
    { id: "accessories", label: "Art Accessories" },
  ],
  brand: [
    { id: "artmaster", label: "ArtMaster" },
    { id: "colorflow", label: "ColorFlow" },
    { id: "sketchpro", label: "SketchPro" },
    { id: "canvascraft", label: "CanvasCraft" },
    { id: "claymaster", label: "ClayMaster" },
    { id: "writeart", label: "WriteArt" },
    { id: "threadcraft", label: "ThreadCraft" },
    { id: "brushmaster", label: "BrushMaster" },
    { id: "journalpro", label: "JournalPro" },
    { id: "colorpro", label: "ColorPro" },
    { id: "clayworks", label: "ClayWorks" },
    { id: "markerart", label: "MarkerArt" },
    { id: "knitcraft", label: "KnitCraft" },
    { id: "gouachepro", label: "GouachePro" },
    { id: "studiopro", label: "StudioPro" },
    { id: "charcoalart", label: "CharcoalArt" },
    { id: "resincraft", label: "ResinCraft" },
    { id: "origamipro", label: "OrigamiPro" },
    { id: "macramecrft", label: "MacrameCraft" },
    { id: "knifemaster", label: "KnifeMaster" },
  ],
};

export const sortOptions = [
  { id: "price-lowtohigh", label: "Price: Low to High" },
  { id: "price-hightolow", label: "Price: High to Low" },
  { id: "title-atoz", label: "Title: A to Z" },
  { id: "title-ztoa", label: "Title: Z to A" },
];

export const addressFormControls = [
  {
    label: "Address",
    name: "address",
    componentType: "input",
    type: "text",
    placeholder: "Enter your address",
  },
  {
    label: "City",
    name: "city",
    componentType: "input",
    type: "text",
    placeholder: "Enter your city",
  },
  {
    label: "Pincode",
    name: "pincode",
    componentType: "input",
    type: "text",
    placeholder: "Enter your pincode",
  },
  {
    label: "Phone",
    name: "phone",
    componentType: "input",
    type: "text",
    placeholder: "Enter your phone number",
  },
  {
    label: "Notes",
    name: "notes",
    componentType: "textarea",
    placeholder: "Enter any additional notes",
  },
];
